### ISSUE TITLE
The Elephant in the Room ... ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/chat#26]
I might be _wrong_ on this, but I _think_ the most important feature of _Chat_ is the fact that messages get routed to all the people who are online as quickly as possible (_preferably instantly_). 

While AWS IOT is a _good_ way of _instantly_ routing the messages to all connected clients/devices, but its _definitely_ not the "_best_" (_or "right"_) way of doing it ... not because the _technology_ or _infrastructure_ is "_worse_" than anything else out there, but simply because you pay _per message_...
Granted its "_only_" ***$5 per 1 Million Messages*** which seems _cheap_ on the surface but can become _silly_ if "_successful_" ... 
## _Example_

Consider the following simple scenario: 
- **10 people (_concurrently_) connected** to the Chat App.
- **1 message sent per minute** of the working day (_average between 09:00 - 18:00 ... 9h ... 540 mins > 540 messages_)
-  **1** "***heartbeat***" (_I'm online message_) sent by ***each client/device per minute***

Each message needs to be routed to all connected clients so 540 messages will result in ***5,400 deliveries***, that seems _fine_ on the _surface_. 
The problem is the "_heartbeat_" i.e. which lets everyone know who is online/available ...
10 clients means 10 x 10 x 540 = ***54k deliveries per day*** 

> ***1,080,000 messages per month*** >> ***$5 Per month***

A more "_successful_" scenario: **100 People Chatting _Concurrently_**
- **100 people connected** to the Chat room during the day.
- 1 message sent each minute of the working day  **540 messages x 100 clients** = ***54k messages delivered*** (_because each message sent has to be delivered to each of the connected clients!!_)
- 1 "_heartbeat_" (_I'm online message_) sent by each client/device per minute of the working day.  

The problem is not the messages. It will "_only_" cost us 
54k \* 20 working days / 1,000,000 = $5 per month for those.
The issue is the "_heartbeat_"  which will be 100 x 100 x 540 (each client sends a heartbeat once per minute which gets forwarded to all other clients for each minute of the working day) = ***5.4 Million msgs per day!***

> ***$22 per day*** >> ***$440 per month***!! 😮 
> 
> _This is **ridiculous**. its like hiring a limo for a trip to the corner shop_. 

So, for an application that requires _presence_ ("_heartbeat_") messages to be sent for _many_ connected people/devices IOT is out of the question. 
- https://cloud.google.com/solutions/real-time-gaming-with-node-js-websocket
- https://pusher.com/pricing
- https://www.firebase.com/pricing.html

![network effect](https://upload.wikimedia.org/wikipedia/commons/0/0d/Network_effect.png)

When [network effect](https://en.wikipedia.org/wiki/Network_effect) goes wrong!

**Comment by trek10-healthsmart** [comment]
You could probably work around needing a heartbeat by using the MQTT Last will and testament to indicate when a user is offline.

**Comment by hauboldj** [comment]
You could probably work around using a heartbeat by using MQTT Last will and testament messages.

**Comment by shortjared** [comment]
Another alternative idea is to have a completely separate topic for heartbeat that you publish to.
Aggregate all statuses in a DDB table or something like that.
Have "status" topic you subscribe all clients to and publish the aggregates once a minute via a lambda function.

(Publish Status Each Minute + Status Topic Subscription Each Minute) \* Connected Clients  = 
(540 + 540) \* 100 = 108,000 per day for heartbeats
$0.54 / day

**Comment by jacktuck** [comment]
@nelsonic 
Yeah the pricing model is quite aggressive at the moment isn't it, i do hope it will come down.

I think your example of presence detection can be solved with life cycle events.

http://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html

Not sure whether these count as messages or not, but would be less frequent than heartbeats?

**Comment by jacktuck** [comment]
Also 
>You can send messages up to 128KB in one block, and will be charged in multiples of 512-bytes

(128 000 bytes) / (512 bytes) = 250

So to send a 128kb message it'll be considered as 250 messages? 👎

**Comment by jacktuck** [comment]
I'm thinking pusher or pubnub might be a good way to go?

**Comment by nelsonic** [comment]
@jacktuck good question and thanks for linking to the life cycle events.
Pusher or PubNub are decent options if the idea is to avoid running your own VMs/Servers,
another `<option>` would be https://www.firebase.com ... 

Luckily, we are busy building a client project using Erlang and "Bare Metal" and will re-use (_and share!_) the knowledge we acquire to run our own infrastructure to ensure end-to-end encryption of messages. 😉

**Comment by nelsonic** [comment]
This conversation should be continued on: https://github.com/dwyl/aws-lambda-iot-chat (_new issue required_)

**Comment by jacktuck** [comment]
Good news.

IOT is now 40% cheaper 

https://aws.amazon.com/blogs/aws/aws-iot-update-better-value-with-new-pricing-model/

**Comment by shortjared** [comment]
FWIW, AppSync with subscriptions would be the canonical choice for this now.

**Comment by nelsonic** [comment]
@shortjared, _yes_, AppSync https://aws.amazon.com/appsync _will_ be a good option.
It's _currently_ in "***Preview***" so not _yet_ "production-ready" ...
![image](https://user-images.githubusercontent.com/194400/35182187-b9e8b58a-fdc7-11e7-830c-633f4ecff424.png)

Pricing looks _reasonable_, especially for a _small_ app!
https://aws.amazon.com/appsync/pricing/
![image](https://user-images.githubusercontent.com/194400/35182280-7573efda-fdc9-11e7-8f5a-1810d4235fab.png)

![image](https://user-images.githubusercontent.com/194400/35182284-8636ed9a-fdc9-11e7-89a6-42849960a8bc.png)

One of the things that we found _annoying_ about developing AWS Lambda Apps 
was _running or testing_ the app _locally_ ... 🙄 

Is the `Serverless` team already working on AppSync support and do the other "IaaS Providers" have something similar so you can make a _generic interface_ that is "cloud agnostic"?

**Comment by jacktuck** [comment]
Thanks for the link guys ❤️

**Comment by jacktuck** [comment]
> One of the things that we found annoying about developing AWS Lambda Apps
was running or testing the app locally ... 

This really rings true.

I guess projects like https://github.com/openfaas/faas help with it somewhat but still a pain point.
