### ISSUE TITLE
Investigate alternatives for WebSockets

### ISSUE THREAD

**Issue by nelsonic** [dwyl/chat#27]
At present we are using AWS IOT but see: #26 
We need a reliable alternative.

**Comment by nelsonic** [comment]
Done: https://github.com/dwyl/technology-stack#the-pete-stack

**Comment by jacktuck** [comment]
but not serverless?

**Comment by jacktuck** [comment]
Do you think SQS with long polling would suffice?

In theory with http2, the connection should stay open, would be interesting to know what the latency difference would be!

**Comment by nelsonic** [comment]
@jacktuck good question! 
I'm actually leaning toward: https://ipfs.io/blog/29-js-ipfs-pubsub
SQS https://aws.amazon.com/sqs/ is a proprietary platform I'd prefer _not_ to invest in. 👍

**Comment by jacktuck** [comment]
Is the underlying idea there to use WebRTC p2p then? Looks like i've got some research on my hands 😆

**Comment by nelsonic** [comment]
@jacktuck yeah, the idea is to _decentralize_ the infrastructure for _several_ good reasons:
+ reduce failure points
+ speed up the system
+ reduce cost (_P2P using WebRTC is virtually free!_)

**Comment by jacktuck** [comment]
@nelsonic Doesn't WebRTC still need signalling and NAT traversal servers on IPFS though - thus not being serverless? I mean, arguably, that's still better than traditional real-time methods i guess. Still a bit of faffing around though.

**Comment by nelsonic** [comment]
@jacktuck yeah, "faffing around" is a good description.
As with all "unfinished" technology, the "early adopters" need to persist to make it "easy" for everyone `else` ... WebRTC is seeing decent traction in certain apps and IPFS is also gaining momentum. If they changed the name to "BitCoinFileSystem" it would take off like a rocket ship! 🤣
