### ISSUE TITLE
Is it okay to leave your AWS PRIVATE KEY in JS source code ?

### ISSUE THREAD

**Issue by kuashe** [dwyl/chat#29]
Hello,

I would like to use aws iot websocket to do exactly what you've done with this application.

I was wondering if leaving your aws key in the js source code was "okay" or this not a real world example and aws key should never be in clear like this ?

**Comment by nelsonic** [comment]
@kuashe _great_ question!
**No**, it's not a _good_ idea to leave a private key in source... 


> _If you know a _better_ way to write OpenSource Code that uses the AWS IOT system without revealing the Private Key, **please tell us**! (thanks)_

***thank you*** for reminding me!! 
this is a "really bad idea"!!! 
and I only did it for a demo at a [meetup](https://github.com/lnug/speakers/issues/72)..._)

In my defence, this AWS account has a _low_ spending limit and alert so if someone wants to use the IOT to run a Botnet or BitCoin mining Op they can certainly `try`...! 😉 

But that's _not_ a good excuse to do something silly like leave the key to my house under the front-door mat and expect that nobody will walk in and take what ever they want... 🤔

**Comment by kuashe** [comment]
This is a real issue . 

Btw your app is awesome, I want to do the same. 

Problem is : leaving a private key in the source bothers me a lot ! 

We need to contact AWS about this .

**Comment by jacktuck** [comment]
You can use AWS Cognito identities i believe

**Comment by kuashe** [comment]
@jacktuck Yes , but only after you've establish connection with your "SECRET_KEY" i found this : https://github.com/dwyl/learn-aws-iot/issues/9 from @nelsonic , the japanese tutorial still has "SECRET_KEY" in the source code even tho it's calling cognito.

**Comment by jacktuck** [comment]
Ah I see. You could have an API GATEWAY endpoint which triggers a LAMBDA which returns a signed url?

**Comment by kuashe** [comment]
It could work but it doesnt really solve the issue.

Ultimately the client still has to use the aws sdk , which mean you ultimately need to do something like this

```
var privateKey = getPrivateKey() //xhr query
aws.endpoint({
PRIVATEKEY : privateKey // Client can debug or log the key in the console
}
```

**Comment by jacktuck** [comment]
Are you sure that's the case?

See http://stackoverflow.com/questions/35439742/how-to-use-aws-iot-to-send-receive-messages-to-from-web-browser

**Comment by kuashe** [comment]
Well , depends i don't know much about cognito.

Does "AWS.CognitoIdentityCredentials()" methods return the private key of the client or the aws account ?
```
var requestUrl = SigV4Utils.getSignedUrl('wss', 'data.iot.us-east-1.amazonaws.com', '/mqtt',
               'iotdevicegateway', 'us-east-1',
                credentials.accessKeyId, credentials.secretAccessKey // Secret key can be logged, credentials.sessionToken);

```

**Comment by jacktuck** [comment]
I'd think it'd be the client (as in Cognito user), but you could log it and check

**Comment by kuashe** [comment]
Okay i'll try , it could be what i need .. Which is not handy as it forces me to use cognito for authentification...

**Comment by nelsonic** [comment]
@kuashe did you figure it out?

**Comment by kuashe** [comment]
I think @jacktuck  was right , returning a signed URL is the recommended way .

Haven't tried but take a look here :  [AWS IOT](http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html)

**Comment by nelsonic** [comment]
@kuashe thanks. 👍
