### ISSUE TITLE
Can we use S3 as our primary data store instead of DynamoDB?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/chat#3]
This _might_ be "_premature_" optimisation, but I don't like the fact that to Scale DynamoDB beyond 20k reads/writes per second we need to contact AWS ... Sure, getting to 20k reads/writes is a pipe-dream at the start of any project, but what are the cost implications?

DynamoDB is $0.25 per GB of stored data. 
S3 is $0.0300 per GB, an order of magnitude less.

Its difficult to precisely pin down how much the cost of a single write to DynamoDB is because they charge for write "_capacity_" effectively you pay for writes-per-second.

So we need an illustration...

**Comment by nelsonic** [comment]
neither. both are _silly_ expensive and have drawbacks. we can do better. 👍

**Comment by esdras** [comment]
I know this is closed for more than a year, but could you please elaborate more? What would you say are the drawbacks of S3? I'm thinking about choosing s3 as a primary data store for a project and a think it is a good fit for that particular case. Interested in hearing your reasons for abandoning the idea, what did you choose instead and why.

Thank you

**Comment by nelsonic** [comment]
@esdras _great_ question and _never_ worry about asking questions on "closed" issues!
My reasoning for using S3 as a data store was simple: 
1. no up-front costs or "provisioning" fees.
2. it scales _infinitely_ and transparently
3. reasonably cheap per write (_though I suggest you monitor your costs!_)

With AWS "Athena" you can now write "SQL" queries against your JSON data stored on S3!
see: https://aws.amazon.com/blogs/aws/amazon-athena-interactive-sql-queries-for-data-in-amazon-s3/

I've _personally_ decided to use the filesystem on the application _server_ hosted on Linode 
for the apps I'm building because it's **_much_ cheaper** per GB of storage and is ***way faster*** too see: https://github.com/dwyl/learn-devops/issues/11

For example: https://github.com/dwyl/hits uses an "Append-only Immutable Log" for storing data.
The logs can be _streamed_ in and out of the Server which is stored on SSD (_much faster than S3_) and is backed up to "traditional" (spinning) hard drives for $2/month so we have reliability. 

Again "_it depends_" on 5 things:
1. what is your volume of writes per second/day/month?
2. size of the payload/data for each record/write
3. how long you are storing each record for
4. will you need to update/overwrite records?
5. how do you intend to read/query the data?

**Comment by nelsonic** [comment]
If cost is _not_ your primary concern then AWS is the way to go. 
In our product the single biggest cost is developer time during "Alpha/Beta Phase",
therefore we _should_ optimise for dev time and use AWS to get to market faster.

_However_ if the product we are building is _successful_ and users end up storing a lot of data,
then using a _cheaper_ solution is _essential_. 
When you consider that you can _reasonably_ easily re-factor the code that uses S3 out to use a cheaper solution it's not a lot of "technical debt" to just go for S3 and _ship_!
once we are "successful" we can always transition to "Colo". see: https://github.com/nelsonic/nelsonic.github.io/blob/master/draft/cloud-vs-colocation.md

**Comment by esdras** [comment]
Great answer! Linode is awesome! ❤️ 

We are already on AWS, so local requests to S3 are free, I basically will persist and retrieve erlang binaries from an ec2 instance to s3, I think/hope it will be a good fit. 😄 

Thank you so much for taking the time to answer my question, sure helped me in my decision.

**Comment by nelsonic** [comment]
@esdras Thank _you_ for asking asking questions! 😉 
Abraço! ❤️  ✅
